"""
邮件发送器
通过 SMTP 发送 HTML 格式的论文日报邮件。
支持 QQ 邮箱 / 163 / Gmail，响应式 HTML 模板。
"""

import logging
import os
import smtplib
import ssl
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class PaperEmailer:
    """邮件发送器。"""

    # 邮件 HTML 模板（内联 CSS，响应式）
    EMAIL_TEMPLATE = """<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{subject}</title>
</head>
<body style="margin:0;padding:0;background-color:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<div style="max-width:680px;margin:0 auto;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.08);">
  <!-- Header -->
  <div style="background:linear-gradient(135deg,#667eea,#764ba2);padding:32px 24px;text-align:center;">
    <h1 style="color:#ffffff;margin:0;font-size:24px;font-weight:700;">arXiv Daily Digest</h1>
    <p style="color:rgba(255,255,255,0.85);margin:8px 0 0;font-size:14px;">{date_str} · {count} papers found</p>
  </div>

  <!-- Body -->
  <div style="padding:24px;">
    {papers_html}
  </div>

  <!-- Footer -->
  <div style="background:#f8f9fa;padding:20px 24px;text-align:center;border-top:1px solid #e9ecef;">
    <p style="color:#868e96;font-size:12px;margin:0;">
      Generated by <a href="{site_url}" style="color:#667eea;text-decoration:none;">Paper Tracker</a>
      · Sent via QQ SMTP
    </p>
    <p style="color:#868e96;font-size:12px;margin:4px 0 0;">
      {categories}
    </p>
  </div>
</div>
</body>
</html>"""

    PAPER_CARD_TMPL = """<div style="border:1px solid #e9ecef;border-radius:8px;padding:16px;margin-bottom:16px;transition:box-shadow 0.2s;">
  <h3 style="margin:0 0 8px;font-size:16px;line-height:1.4;">
    <a href="{url}" style="color:#1a1a2e;text-decoration:none;">{title}</a>
  </h3>
  <p style="color:#495057;font-size:13px;margin:0 0 8px;">{authors}</p>
  <p style="color:#6c757d;font-size:13px;line-height:1.6;margin:0 0 10px;">{abstract}</p>
  <div style="display:flex;flex-wrap:wrap;gap:6px;font-size:12px;">
    {badges}
  </div>
  {recommend_html}
  {summary_html}
</div>"""

    BADGE_TMPL = '<span style="background:{bg};color:{fg};padding:2px 8px;border-radius:12px;font-weight:500;">{text}</span>'

    def __init__(self, config: Any):
        """
        Args:
            config: ConfigManager 实例
        """
        self.config = config
        self.enabled: bool = config.get("email.enabled", False)

        # SMTP 配置
        self.smtp_server: str = config.get("email.smtp_server", "smtp.qq.com")
        self.smtp_port: int = config.get("email.smtp_port", 465)
        self.tls: str = config.get("email.tls", "ssl")
        self.use_env: bool = config.get("email.use_env", True)

        # 邮件内容配置
        self.subject_prefix: str = config.get("email.subject_prefix", "[arXiv Daily]")
        self.max_items: int = config.get("email.max_items", 15)
        self.include_pdf_links: bool = config.get("email.include_pdf_links", True)
        self.include_score: bool = config.get("email.include_score", True)
        self.detail: str = config.get("email.detail", "full")

        # 从环境变量读取敏感信息
        self.user: str = os.environ.get("EMAIL_USER", "") or config.get("email.user", "")
        self.password: str = os.environ.get("EMAIL_PASSWORD", "") or config.get("email.password", "")
        self.sender: str = os.environ.get("EMAIL_SENDER", "") or config.get("email.sender", self.user)
        self.recipient: str = os.environ.get("EMAIL_RECIPIENT", "") or config.get("email.recipient", self.user)

    # ------------------------------------------------------------------
    # 公共接口
    # ------------------------------------------------------------------

    def send(self, papers: List[Dict], categories: Optional[List[str]] = None) -> bool:
        """
        发送邮件日报。

        Args:
            papers: 论文列表
            categories: 检索的 arXiv 分类

        Returns:
            发送是否成功
        """
        if not self.enabled:
            logger.info("邮件发送已禁用，跳过")
            return True

        if not self.password:
            logger.error("邮件密码未配置（EMAIL_PASSWORD 环境变量）")
            return False

        if not papers:
            logger.info("无论文，跳过邮件发送")
            return True

        # 限制数量
        papers = papers[: self.max_items]

        # 构建邮件
        subject = self._build_subject(papers)
        html_body = self._build_html(papers, categories)

        return self._send_email(subject, html_body)

    def test_send(self) -> bool:
        """发送测试邮件，验证 SMTP 配置。"""
        logger.info("发送测试邮件...")
        subject = f"{self.subject_prefix} Test Email"

        html = f"""<!DOCTYPE html>
<html><body style="font-family:sans-serif;padding:20px;">
<h2>Paper Tracker - 测试邮件</h2>
<p>如果你收到这封邮件，说明 SMTP 配置正确。</p>
<p>发送时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
</body></html>"""

        return self._send_email(subject, html)

    # ------------------------------------------------------------------
    # 内部
    # ------------------------------------------------------------------

    def _build_subject(self, papers: List[Dict]) -> str:
        """构建邮件主题。"""
        count = len(papers)
        date_str = datetime.now().strftime("%Y-%m-%d")
        return f"{self.subject_prefix} {date_str} - {count} papers"

    def _build_html(self, papers: List[Dict], categories: Optional[List[str]] = None) -> str:
        """构建邮件 HTML 内容。"""
        papers_html_parts = []
        for paper in papers:
            title = paper.get("title", "Untitled")
            authors = ", ".join(paper.get("authors", [])[:5])
            if len(paper.get("authors", [])) > 5:
                authors += " et al."

            abstract = paper.get("abstract", "")
            abstract_en = paper.get("summary_en", "")
            abstract_zh = paper.get("summary_zh", "")

            if self.detail == "simple":
                abstract_text = (abstract_zh or abstract_en or abstract)[:150] + "..."
            else:
                abstract_text = abstract[:300] + ("..." if len(abstract) > 300 else "")

            entry_url = paper.get("entry_url", "")
            if not entry_url:
                entry_url = f"https://arxiv.org/abs/{paper.get('arxiv_id', '')}"

            # 构建 badges
            badges = self._build_badges(paper)

            # 本地推荐
            recommend_html = ""
            rec = paper.get("recommend", {})
            if rec and self.include_score:
                score = rec.get("score", 0)
                matches = rec.get("matches", [])
                if matches:
                    match_items = "".join(
                        f'<li style="margin-bottom:2px;">{m["title"][:60]} ({m["score"]:.2f})</li>'
                        for m in matches[:3]
                    )
                    recommend_html = f"""<div style="background:#f0f4ff;border-radius:6px;padding:8px 12px;margin-top:8px;">
  <p style="margin:0 0 4px;font-size:12px;color:#667eea;font-weight:600;">Local Recommendations (score: {score:.2f})</p>
  <ul style="margin:0;padding-left:16px;font-size:12px;color:#495057;">{match_items}</ul>
</div>"""

            # LLM 摘要
            summary_html = ""
            if self.detail == "full" and (abstract_zh or abstract_en):
                parts = []
                if abstract_zh:
                    parts.append(f'<p style="margin:4px 0;font-size:12px;color:#7950f2;"><b>CN:</b> {abstract_zh}</p>')
                if abstract_en and self.config.get("llm_summary.lang") in ("en", "both"):
                    parts.append(f'<p style="margin:4px 0;font-size:12px;color:#1c7ed6;"><b>EN:</b> {abstract_en}</p>')
                if parts:
                    summary_html = f'<div style="background:#f8f9fa;border-radius:6px;padding:8px 12px;margin-top:8px;">{"".join(parts)}</div>'

            papers_html_parts.append(
                self.PAPER_CARD_TMPL.format(
                    title=title,
                    url=entry_url,
                    authors=authors,
                    abstract=abstract_text,
                    badges="".join(badges) if badges else "",
                    recommend_html=recommend_html,
                    summary_html=summary_html,
                )
            )

        papers_html = "\n".join(papers_html_parts)
        date_str = datetime.now().strftime("%Y-%m-%d %A")
        cat_str = " · ".join(categories) if categories else "All Categories"

        return self.EMAIL_TEMPLATE.format(
            subject=self._build_subject(papers),
            date_str=date_str,
            count=len(papers),
            papers_html=papers_html,
            site_url="",
            categories=cat_str,
        )

    def _build_badges(self, paper: Dict) -> List[str]:
        """构建论文标签。"""
        badges = []

        # arXiv 分类
        cats = paper.get("categories", [])
        if cats:
            for cat in cats[:2]:
                badges.append(
                    self.BADGE_TMPL.format(
                        bg="#e8f4f8", fg="#0c6787", text=cat
                    )
                )

        # 期刊匹配
        journal = paper.get("matched_journal", "")
        if journal:
            badges.append(
                self.BADGE_TMPL.format(
                    bg="#fff3cd", fg="#856404", text=f"Venue: {journal}"
                )
            )

        # 引用量
        citations = paper.get("citation_count", 0)
        if citations > 0:
            badges.append(
                self.BADGE_TMPL.format(
                    bg="#e8e8e8", fg="#333333", text=f"Cited: {citations}"
                )
            )

        # PDF 链接
        pdf_url = paper.get("pdf_url", "")
        if pdf_url and self.include_pdf_links:
            badges.append(
                f'<a href="{pdf_url}" style="background:#dc3545;color:#ffffff;padding:2px 8px;border-radius:12px;font-weight:500;text-decoration:none;font-size:12px;">PDF</a>'
            )

        # GitHub 链接
        github = paper.get("github_link", "")
        if github:
            badges.append(
                f'<a href="{github}" style="background:#24292e;color:#ffffff;padding:2px 8px;border-radius:12px;font-weight:500;text-decoration:none;font-size:12px;">Code</a>'
            )

        return badges

    def _send_email(self, subject: str, html_body: str) -> bool:
        """通过 SMTP 发送邮件。"""
        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = self.sender
            msg["To"] = self.recipient
            msg.attach(MIMEText(html_body, "html", "utf-8"))

            if self.tls == "ssl":
                context = ssl.create_default_context()
                with smtplib.SMTP_SSL(self.smtp_server, self.smtp_port, context=context) as server:
                    server.login(self.user, self.password)
                    server.sendmail(self.sender, self.recipient, msg.as_string())
            else:
                with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                    if self.tls == "starttls":
                        server.starttls()
                    server.login(self.user, self.password)
                    server.sendmail(self.sender, self.recipient, msg.as_string())

            logger.info(f"邮件发送成功: {subject}")
            return True

        except smtplib.SMTPAuthenticationError:
            logger.error("SMTP 认证失败，请检查邮箱账号和授权码")
            return False
        except smtplib.SMTPException as e:
            logger.error(f"SMTP 错误: {e}")
            return False
        except Exception as e:
            logger.error(f"邮件发送失败: {e}")
            return False
