"""
站点生成器
生成 GitHub Pages 静态站点，包含历史日报归档和首页索引。
"""

import json
import logging
import os
import shutil
from datetime import datetime
from typing import Any, Dict, List

logger = logging.getLogger(__name__)


class SiteBuilder:
    """GitHub Pages 站点生成器。"""

    # 站点基础模板
    INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  :root {{
    --bg: {bg};
    --text: {text};
    --card-bg: {card_bg};
    --border: {border};
    --accent: {accent};
    --accent-light: {accent_light};
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg);
    color: var(--text);
    line-height: 1.6;
  }}
  .container {{ max-width: 800px; margin: 0 auto; padding: 24px 16px; }}
  header {{
    text-align: center;
    padding: 48px 16px 32px;
    background: linear-gradient(135deg, {accent}, {accent_dark});
    color: #ffffff;
  }}
  header h1 {{ font-size: 28px; margin-bottom: 8px; }}
  header p {{ opacity: 0.85; font-size: 14px; }}
  .run-card {{
    background: var(--card-bg);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 16px;
    margin-bottom: 12px;
    transition: box-shadow 0.2s;
  }}
  .run-card:hover {{ box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
  .run-card a {{ color: var(--accent); text-decoration: none; font-weight: 600; font-size: 16px; }}
  .run-card .meta {{ color: #868e96; font-size: 13px; margin-top: 4px; }}
  .empty {{ text-align: center; padding: 48px 16px; color: #868e96; }}
  footer {{ text-align: center; padding: 24px 16px; color: #868e96; font-size: 12px; }}
</style>
</head>
<body>
<header>
  <h1>{title}</h1>
  <p>{subtitle}</p>
</header>
<div class="container">
  <h2 style="font-size:18px;margin-bottom:16px;">History ({count} runs)</h2>
  {runs_html}
</div>
<footer>
  Generated by Paper Tracker · {now_str}
</footer>
</body>
</html>"""

    DAILY_TEMPLATE = """<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{date_str} - {title}</title>
<style>
  :root {{
    --bg: {bg};
    --text: {text};
    --card-bg: {card_bg};
    --border: {border};
    --accent: {accent};
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg);
    color: var(--text);
    line-height: 1.6;
  }}
  .container {{ max-width: 860px; margin: 0 auto; padding: 24px 16px; }}
  header {{
    text-align: center;
    padding: 40px 16px 24px;
    background: linear-gradient(135deg, {accent}, {accent_dark});
    color: #ffffff;
  }}
  header h1 {{ font-size: 22px; }}
  header p {{ opacity: 0.85; font-size: 13px; margin-top: 4px; }}
  .back-link {{
    display: inline-block;
    margin: 16px 0;
    color: var(--accent);
    text-decoration: none;
    font-size: 14px;
  }}
  .paper-card {{
    background: var(--card-bg);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 16px;
    margin-bottom: 12px;
  }}
  .paper-card h3 {{ font-size: 16px; margin-bottom: 6px; }}
  .paper-card h3 a {{ color: var(--text); text-decoration: none; }}
  .paper-card h3 a:hover {{ color: var(--accent); }}
  .paper-card .authors {{ color: #495057; font-size: 13px; margin-bottom: 6px; }}
  .paper-card .abstract {{ color: #6c757d; font-size: 13px; line-height: 1.6; }}
  .badge {{
    display: inline-block;
    padding: 2px 8px;
    border-radius: 12px;
    font-size: 11px;
    font-weight: 500;
    margin: 2px;
  }}
  footer {{ text-align: center; padding: 24px; color: #868e96; font-size: 12px; }}
</style>
</head>
<body>
<header>
  <h1>{date_str}</h1>
  <p>{count} papers from arXiv</p>
</header>
<div class="container">
  <a href="index.html" class="back-link">← Back to history</a>
  {papers_html}
</div>
<footer>Generated by Paper Tracker</footer>
</body>
</html>"""

    def __init__(self, config: Any):
        """
        Args:
            config: ConfigManager 实例
        """
        self.config = config
        self.site_dir: str = config.get("site.dir", "docs")
        self.site_title: str = config.get("site.title", "Paper Tracker - arXiv Daily")
        self.keep_runs: int = config.get("site.keep_runs", 30)
        self.theme: str = config.get("site.theme", "light")
        self.accent: str = config.get("site.accent", "#2563eb")

    # ------------------------------------------------------------------
    # 公共接口
    # ------------------------------------------------------------------

    def build(self, papers: List[Dict], date_str: str) -> str:
        """
        构建站点：生成当日日报页面 + 更新首页索引。

        Args:
            papers: 论文列表
            date_str: 日期字符串（如 2026-07-07）

        Returns:
            生成的日报页面路径
        """
        os.makedirs(self.site_dir, exist_ok=True)

        # 生成日报页面
        daily_path = self._build_daily(papers, date_str)

        # 更新首页索引
        self._build_index()

        # 清理旧日报
        self._cleanup_old_runs()

        logger.info(f"站点生成完成: {daily_path}")
        return daily_path

    # ------------------------------------------------------------------
    # 内部
    # ------------------------------------------------------------------

    def _build_daily(self, papers: List[Dict], date_str: str) -> str:
        """生成单日日报页面。"""
        papers_html_parts = []
        for paper in papers:
            title = paper.get("title", "Untitled")
            authors = ", ".join(paper.get("authors", [])[:5])
            if len(paper.get("authors", [])) > 5:
                authors += " et al."
            abstract = paper.get("abstract", "")[:400]
            if len(paper.get("abstract", "")) > 400:
                abstract += "..."

            entry_url = paper.get("entry_url", "")
            if not entry_url:
                entry_url = f"https://arxiv.org/abs/{paper.get('arxiv_id', '')}"

            badges = []
            cats = paper.get("categories", [])
            for cat in cats[:3]:
                badges.append(f'<span class="badge" style="background:#e8f4f8;color:#0c6787;">{cat}</span>')
            journal = paper.get("matched_journal", "")
            if journal:
                badges.append(f'<span class="badge" style="background:#fff3cd;color:#856404;">{journal}</span>')
            cit = paper.get("citation_count", 0)
            if cit:
                badges.append(f'<span class="badge" style="background:#e8e8e8;color:#333;">Cited: {cit}</span>')

            papers_html_parts.append(f"""<div class="paper-card">
  <h3><a href="{entry_url}" target="_blank">{title}</a></h3>
  <p class="authors">{authors}</p>
  <p class="abstract">{abstract}</p>
  <div style="margin-top:8px;">{"".join(badges)}</div>
</div>""")

        theme_colors = self._get_theme_colors()
        html = self.DAILY_TEMPLATE.format(
            lang="en",
            date_str=date_str,
            title=self.site_title,
            count=len(papers),
            papers_html="\n".join(papers_html_parts),
            **theme_colors,
        )

        fname = f"daily-{date_str}.html"
        file_path = os.path.join(self.site_dir, fname)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(html)

        return file_path

    def _build_index(self) -> None:
        """构建/更新首页索引。"""
        # 扫描所有日报文件
        daily_files = []
        if os.path.isdir(self.site_dir):
            for fname in os.listdir(self.site_dir):
                if fname.startswith("daily-") and fname.endswith(".html"):
                    # 提取日期
                    date_part = fname.replace("daily-", "").replace(".html", "")
                    file_path = os.path.join(self.site_dir, fname)
                    mtime = os.path.getmtime(file_path)
                    daily_files.append((date_part, fname, mtime))

        # 按时间降序排列
        daily_files.sort(key=lambda x: x[2], reverse=True)

        runs_html_parts = []
        for date_part, fname, mtime in daily_files:
            dt = datetime.fromtimestamp(mtime)
            runs_html_parts.append(f"""<div class="run-card">
  <a href="{fname}">{date_part}</a>
  <p class="meta">Generated: {dt.strftime('%Y-%m-%d %H:%M')}</p>
</div>""")

        runs_html = "\n".join(runs_html_parts) if runs_html_parts else '<div class="empty">No daily digests yet.</div>'

        theme_colors = self._get_theme_colors()
        html = self.INDEX_TEMPLATE.format(
            lang="en",
            title=self.site_title,
            subtitle="arXiv Daily Paper Digest",
            count=len(daily_files),
            runs_html=runs_html,
            now_str=datetime.now().strftime("%Y-%m-%d %H:%M"),
            **theme_colors,
        )

        index_path = os.path.join(self.site_dir, "index.html")
        with open(index_path, "w", encoding="utf-8") as f:
            f.write(html)

    def _cleanup_old_runs(self) -> None:
        """清理超出保留数量的旧日报。"""
        daily_files = []
        for fname in os.listdir(self.site_dir):
            if fname.startswith("daily-") and fname.endswith(".html"):
                file_path = os.path.join(self.site_dir, fname)
                mtime = os.path.getmtime(file_path)
                daily_files.append((mtime, file_path))

        daily_files.sort(key=lambda x: x[0], reverse=True)

        for _, file_path in daily_files[self.keep_runs:]:
            os.remove(file_path)
            logger.info(f"清理旧日报: {file_path}")

    def _get_theme_colors(self) -> Dict[str, str]:
        """获取主题颜色配置。"""
        if self.theme == "dark":
            return {
                "bg": "#1a1a2e",
                "text": "#e0e0e0",
                "card_bg": "#16213e",
                "border": "#2a2a4a",
                "accent": self.accent,
                "accent_light": "#3b82f6",
                "accent_dark": "#1d4ed8",
            }
        else:
            return {
                "bg": "#f8f9fa",
                "text": "#212529",
                "card_bg": "#ffffff",
                "border": "#e9ecef",
                "accent": self.accent,
                "accent_light": "#3b82f6",
                "accent_dark": "#1d4ed8",
            }
